stages:
  - compile
  - push
 # - scan

compile:
  image: registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
  stage: compile
  script:
    - cd build-integration && ./mvnw package
  artifacts:
    paths:
      - target
    expire_in: 1 week

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/jmhbnz/fast-acs-demo/demo:latest .
    - docker push $CI_REGISTRY/jmhbnz/fast-acs-demo/image:latest

# scan:
#   stage: scan
#   script:
#     - >
#         curl -k -L -H "Authorization: Bearer $ROX_API_TOKEN"
#         https://$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux --output ./roxctl
#     - chmod a+x ./roxctl
#     - ./roxctl image scan -e $ROX_CENTRAL_ENDPOINT --force --image my.registry/repo/image:latest
#     - ./roxctl image check -e $ROX_CENTRAL_ENDPOINT --image my.registry/repo/image:latest
