stages:
  - Check
  - Compile
  - Build image
  - Scan image

Check policy:
  stage: Check
  script:
    - >
        curl -k -L -H "Authorization: Bearer $ROX_API_TOKEN"
        "$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux" --output ./roxctl
    - chmod a+x ./roxctl
    - ./roxctl deployment check -e $ROX_CENTRAL_ENDPOINT:443 --file deployment.yaml --insecure-skip-tls-verify

Compile code:
  image: registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
  stage: Compile
  script:
    - cd build-integration && ./mvnw package
  artifacts:
    paths:
      - build-integration/target/
    expire_in: 1 week

Build image:
  image: docker:20.10.16
  stage: Build image
  services:
    - docker:20.10.16-dind
  script:
    - ls -la build-integration/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/jmhbnz/fast-acs-demo/demo:latest .
    - docker push $CI_REGISTRY/jmhbnz/fast-acs-demo/demo:latest
  needs:
    - job: Compile code
      artifacts: true

Scan image:
  stage: Scan image
  script:
    - >
        curl -k -L -H "Authorization: Bearer $ROX_API_TOKEN"
        "$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux" --output ./roxctl
    - chmod a+x ./roxctl
    - ./roxctl image scan -e $ROX_CENTRAL_ENDPOINT:443 --force --image $CI_REGISTRY/jmhbnz/fast-acs-demo/demo:latest
    - ./roxctl image check -e $ROX_CENTRAL_ENDPOINT:443 --image $CI_REGISTRY/jmhbnz/fast-acs-demo/demo:latest
