image: registry.access.redhat.com/ubi9/openjdk-17-runtime:latest

stages:
  - build
  - scan

build:
  stage: build
  script:
    - cd build-integration && ./mvnw compile

scan:
  stage: scan
  script:
    - >
        curl -k -L -H "Authorization: Bearer $ROX_API_TOKEN"
        https://$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux --output ./roxctl
    - chmod a+x ./roxctl
    - ./roxctl image scan -e $ROX_CENTRAL_ENDPOINT --force --image my.registry/repo/image:latest
    - ./roxctl image check -e $ROX_CENTRAL_ENDPOINT --image my.registry/repo/image:latest
